version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    restart: always
    logging:
      driver: "json-file"
    networks:
      - mongo_net
  matilda:
    image: davivcu/matilda:latest
    volumes: 
      - ./configuration:/configuration
    restart: always
    logging:
      driver: "json-file"
    ports:
      - 5000:5000
    networks:
      - mongo_net
networks:
  mongo_net:
    driver: bridge