version: '3'
services:
  lida:
    image: davivcu/lida2:latest
    volumes: 
      - ./matilda_conf:/app/matilda_conf
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
  mongodb:
    image: mongo:bionic
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
