version: '3'
services:
  matilda:
    image: davivcu/matilda:beta
    volumes: 
      - ./configuration:/configuration
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
  mongodb:
    image: mongo:bionic
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"