version: '3.6'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    restart: always
    logging:
      driver: "json-file"
    networks:
      - mongo_net
    ports:
      - 27017:27017
  matilda:
    image: davivcu/matilda:beta
    volumes: 
      - ./configuration:/configuration
    restart: always
    logging:
      driver: "json-file"
    ports:
      - 5000:5000
    networks:
      - mongo_net
  nginx:
    image: nginx
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    restart: always
    networks:
      - mongo_net
    logging:
      driver: "json-file"
    ports:
      - 80:80
      - 443:443
networks:
  mongo_net:
    driver: bridge